version: '3.8'
services:      
    spring-generate-database-new:
        container_name: pokedex-database
        image: postgres:12.5-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: pokedex-db